apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appserver.name}}-service
spec:
  selector:
    app: {{.Values.appserver.name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{.Values.appserver.image.exposedPort}}
  type: {{.Values.appserver.service.type}}
