apiVersion: v1
kind: Service
metadata:
  name: {{.Values.nginx.name}}-service
spec:
  selector:
    app: {{.Values.nginx.name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{.Values.nginx.image.exposedPort}}
  type: {{.Values.nginx.service.type}}
