
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.userservice.name}}-service
spec:
  selector:
    app: {{.Values.userservice.name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{.Values.userservice.image.exposedPort}}
  type: {{.Values.userservice.service.type}}