apiVersion: apps/v1
kind: Deployment
metadata:
  name: appserver-deployment
  labels:
    app: appserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      labels:
        app: appserver
    spec:
      containers:
        - name: appserver
          image: arjunscorpio2000/appserver:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production